# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'array_sensor.ui'
#
# Created: Wed Aug 17 13:58:57 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ArraySensorMainWindow(object):
    def setupUi(self, ArraySensorMainWindow):
        ArraySensorMainWindow.setObjectName("ArraySensorMainWindow")
        ArraySensorMainWindow.resize(700, 699)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ArraySensorMainWindow.sizePolicy().hasHeightForWidth())
        ArraySensorMainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(ArraySensorMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_2 = QtGui.QWidget(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timeLabel = QtGui.QLabel(self.widget_2)
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout.addWidget(self.timeLabel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.levelLabel = QtGui.QLabel(self.widget_2)
        self.levelLabel.setObjectName("levelLabel")
        self.horizontalLayout.addWidget(self.levelLabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.debugRadioButton = QtGui.QRadioButton(self.widget_2)
        self.debugRadioButton.setObjectName("debugRadioButton")
        self.horizontalLayout.addWidget(self.debugRadioButton)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.mpl = MplWidget(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setObjectName("mpl")
        self.verticalLayout_4.addWidget(self.mpl)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.serialPortLineEdit = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serialPortLineEdit.sizePolicy().hasHeightForWidth())
        self.serialPortLineEdit.setSizePolicy(sizePolicy)
        self.serialPortLineEdit.setObjectName("serialPortLineEdit")
        self.horizontalLayout_3.addWidget(self.serialPortLineEdit)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.startPushButton = QtGui.QPushButton(self.frame_3)
        self.startPushButton.setObjectName("startPushButton")
        self.horizontalLayout_3.addWidget(self.startPushButton)
        self.stopPushButton = QtGui.QPushButton(self.frame_3)
        self.stopPushButton.setObjectName("stopPushButton")
        self.horizontalLayout_3.addWidget(self.stopPushButton)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtGui.QLabel(self.frame_5)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.thresholdLineEdit = QtGui.QLineEdit(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thresholdLineEdit.sizePolicy().hasHeightForWidth())
        self.thresholdLineEdit.setSizePolicy(sizePolicy)
        self.thresholdLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.thresholdLineEdit.setObjectName("thresholdLineEdit")
        self.horizontalLayout_4.addWidget(self.thresholdLineEdit)
        spacerItem4 = QtGui.QSpacerItem(65, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.label_3 = QtGui.QLabel(self.frame_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.calibrationLineEdit = QtGui.QLineEdit(self.frame_5)
        self.calibrationLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.calibrationLineEdit.setObjectName("calibrationLineEdit")
        self.horizontalLayout_4.addWidget(self.calibrationLineEdit)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.takeBackgroundPushButton = QtGui.QPushButton(self.frame_2)
        self.takeBackgroundPushButton.setObjectName("takeBackgroundPushButton")
        self.verticalLayout_2.addWidget(self.takeBackgroundPushButton)
        self.loadBackgroundPushButton = QtGui.QPushButton(self.frame_2)
        self.loadBackgroundPushButton.setObjectName("loadBackgroundPushButton")
        self.verticalLayout_2.addWidget(self.loadBackgroundPushButton)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.deleteBackgroundPushButton = QtGui.QPushButton(self.frame_2)
        self.deleteBackgroundPushButton.setObjectName("deleteBackgroundPushButton")
        self.verticalLayout_5.addWidget(self.deleteBackgroundPushButton)
        self.saveBackgroundPushButton = QtGui.QPushButton(self.frame_2)
        self.saveBackgroundPushButton.setObjectName("saveBackgroundPushButton")
        self.verticalLayout_5.addWidget(self.saveBackgroundPushButton)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.setLogPushButton = QtGui.QPushButton(self.frame_2)
        self.setLogPushButton.setObjectName("setLogPushButton")
        self.verticalLayout_6.addWidget(self.setLogPushButton)
        self.widget = QtGui.QWidget(self.frame_2)
        self.widget.setObjectName("widget")
        self.verticalLayout_6.addWidget(self.widget)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.startLogPushButton = QtGui.QPushButton(self.frame_2)
        self.startLogPushButton.setObjectName("startLogPushButton")
        self.verticalLayout.addWidget(self.startLogPushButton)
        self.stopLogPushButton = QtGui.QPushButton(self.frame_2)
        self.stopLogPushButton.setObjectName("stopLogPushButton")
        self.verticalLayout.addWidget(self.stopLogPushButton)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logFileLabel = QtGui.QLabel(self.frame_4)
        self.logFileLabel.setObjectName("logFileLabel")
        self.horizontalLayout_2.addWidget(self.logFileLabel)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout_3.addWidget(self.frame_4)
        ArraySensorMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ArraySensorMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 23))
        self.menubar.setObjectName("menubar")
        ArraySensorMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ArraySensorMainWindow)
        self.statusbar.setObjectName("statusbar")
        ArraySensorMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ArraySensorMainWindow)
        QtCore.QMetaObject.connectSlotsByName(ArraySensorMainWindow)

    def retranslateUi(self, ArraySensorMainWindow):
        ArraySensorMainWindow.setWindowTitle(QtGui.QApplication.translate("ArraySensorMainWindow", "Capillary Array Sensor", None, QtGui.QApplication.UnicodeUTF8))
        self.timeLabel.setText(QtGui.QApplication.translate("ArraySensorMainWindow", "Time:         ", None, QtGui.QApplication.UnicodeUTF8))
        self.levelLabel.setText(QtGui.QApplication.translate("ArraySensorMainWindow", "Fluid Level:          ", None, QtGui.QApplication.UnicodeUTF8))
        self.debugRadioButton.setText(QtGui.QApplication.translate("ArraySensorMainWindow", "debug", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ArraySensorMainWindow", "Serial Port", None, QtGui.QApplication.UnicodeUTF8))
        self.serialPortLineEdit.setToolTip(QtGui.QApplication.translate("ArraySensorMainWindow", "set serial port address", None, QtGui.QApplication.UnicodeUTF8))
        self.startPushButton.setToolTip(QtGui.QApplication.translate("ArraySensorMainWindow", "start acquiring data from sensor", None, QtGui.QApplication.UnicodeUTF8))
        self.startPushButton.setText(QtGui.QApplication.translate("ArraySensorMainWindow", "        Start      ", None, QtGui.QApplication.UnicodeUTF8))
        self.stopPushButton.setToolTip(QtGui.QApplication.translate("ArraySensorMainWindow", "stop acquisition form sensor", None, QtGui.QApplication.UnicodeUTF8))
        self.stopPushButton.setText(QtGui.QApplication.translate("ArraySensorMainWindow", "       Stop        ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ArraySensorMainWindow", "Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ArraySensorMainWindow", "Calibration (nL/mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.takeBackgroundPushButton.setToolTip(QtGui.QApplication.translate("ArraySensorMainWindow", "take background reading of capillary for equalization", None, QtGui.QApplication.UnicodeUTF8))
        self.takeBackgroundPushButton.setText(QtGui.QApplication.translate("ArraySensorMainWindow", "Take Background", None, QtGui.QApplication.UnicodeUTF8))
        self.loadBackgroundPushButton.setToolTip(QtGui.QApplication.translate("ArraySensorMainWindow", "load background reading from file", None, QtGui.QApplication.UnicodeUTF8))
        self.loadBackgroundPushButton.setText(QtGui.QApplication.translate("ArraySensorMainWindow", "Load Background", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteBackgroundPushButton.setToolTip(QtGui.QApplication.translate("ArraySensorMainWindow", "delete current background reading", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteBackgroundPushButton.setText(QtGui.QApplication.translate("ArraySensorMainWindow", "Delete Background", None, QtGui.QApplication.UnicodeUTF8))
        self.saveBackgroundPushButton.setToolTip(QtGui.QApplication.translate("ArraySensorMainWindow", "save current background reading to file", None, QtGui.QApplication.UnicodeUTF8))
        self.saveBackgroundPushButton.setText(QtGui.QApplication.translate("ArraySensorMainWindow", "Save Background", None, QtGui.QApplication.UnicodeUTF8))
        self.setLogPushButton.setToolTip(QtGui.QApplication.translate("ArraySensorMainWindow", "set current data log file", None, QtGui.QApplication.UnicodeUTF8))
        self.setLogPushButton.setText(QtGui.QApplication.translate("ArraySensorMainWindow", " Set Log File  ", None, QtGui.QApplication.UnicodeUTF8))
        self.startLogPushButton.setToolTip(QtGui.QApplication.translate("ArraySensorMainWindow", "start logging data to file", None, QtGui.QApplication.UnicodeUTF8))
        self.startLogPushButton.setText(QtGui.QApplication.translate("ArraySensorMainWindow", "Start Logging", None, QtGui.QApplication.UnicodeUTF8))
        self.stopLogPushButton.setToolTip(QtGui.QApplication.translate("ArraySensorMainWindow", "stop logging data to file", None, QtGui.QApplication.UnicodeUTF8))
        self.stopLogPushButton.setText(QtGui.QApplication.translate("ArraySensorMainWindow", "Stop Logging", None, QtGui.QApplication.UnicodeUTF8))
        self.logFileLabel.setText(QtGui.QApplication.translate("ArraySensorMainWindow", "Log File: ", None, QtGui.QApplication.UnicodeUTF8))

from mplwidget import MplWidget
